.TH UNRAR 1 2021-11-03 "" "RAR archiver"
.SH NAME
unrar \- extract files from rar archives
.SH SYNOPSIS
.B unrar
.IR command " [" \-switch " \&...\&] " archive \
" [" file " \&...\&] [@" listfiles " \&...\&] [" path " \&...\&] [" path_to_extract "/]"
.SH "DESCRIPTION"
This manual page documents briefly the
.B unrar
command.
.br
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.br
Commands and options described here are as of
.B unrar
7.11.
.PP
.B unrar
is a program for extracting .rar archives.
.SH USAGE
.TP
.B archive
Archive file name in RAR or other supported format.
If archive file uses RAR multiple volume format, specify only first volume file
name as
.B archive
file name.
.TP
.B file ...
File path name to extract.
You can specify more path names at one time.
.TP
.B @listfiles ...
If argument starts with "@", unrar uses
.B listfile
as file path list file.
This list file includes file path list to extract from archive file.
You can use 2 or more list files at one time.
.br
File list uses one line for one file path.
And blank line is ignored.
.br
This file is used to extract many file path names in one time that your
shell can't accept.
.TP
.B path_to_extract
If last argument is ended with "/", unrar uses
.B path_to_extract
as file extraction target path.
.SH COMMANDS
After the program name comes a command and then optional switches with
dashes before them.
A summary of commands is included below.
For a complete description, run
.B unrar
without options.
.TP
.B e
Extract files to current directory.
.TP
.B l[t[a],b]
List archive content [technical[all], bare].
.TP
.B p
Print file to stdout.
.TP
.B t
Test archive files.
.TP
.B v[t[a],b]
Verbosely list archive [technical[all], bare].
.TP
.B x
Extract files with full path.
.SH OPTIONS
.B NOTE:
Every switch must be separated by a whitespace.
You cannot put them together.
.TP
.B \-\-
Stop switches scanning.
.TP
.B \-@[+]
Disable [enable] file lists.
.TP
.B \-ad[1,2]
Alternate destination path.
.TP
.B \-ag[format]
Generate archive name using the current date.
.TP
.B \-ai
Ignore file attributes.
.TP
.B \-ap<path>
Set path inside archive.
.TP
.B \-c\-
Disable comments show.
.TP
.B \-cfg-
Disable read configuration.
.TP
.B \-cl
Convert names to lower case.
.TP
.B \-cu
Convert names to upper case.
.TP
.B \-dh
Open shared files.
.TP
.B \-ep
Exclude paths from names.
.TP
.B \-ep3
Expand paths to full name.
.TP
.B \-ep4<path>
Exclude the path prefix from names.
.TP
.B \-f
Freshen files.
.TP
.B \-id[c,d,n,p,q]
Display or disable messages.
.TP
.B \-ierr
Send all messages to stderr.
.TP
.B \-inul
Disable all messages.
.TP
.B \-kb
Keep broken extracted files.
.TP
.B \-me[par]
Set encryption parameters.
.TP
.B \-n<file>
Additionally filter included files.
.TP
.B \-n@
Read additional filter masks from stdin.
.TP
.B \-n@<list>
Read additional filter masks from list file.
.TP
.B \-o+
Overwrite existing files.
.TP
.B \-o\-
Do not overwrite existing files.
.TP
.B \-ol[a,-]
Process symbolic links as the link [absolute paths, skip].
.TP
.B \-om[-|1][=lst]
Propagate Mark of the Web.
.TP
.B \-op<path>
Set the output path for extracted files.
.TP
.B \-or
Rename files automatically.
.TP
.B \-ow
Save or restore file owner and group.
.TP
.BI \-p[password]
Set password.
.TP
.B \-p\-
Do not query password.
.TP
.B \-r
Recurse subdirectories.
.TP
.B \-sc<chr>[obj]
Specify the character set.
.TP
.B \-si[name]
Read data from standard input (stdin).
.TP
.B \-sl<size>
Process files with size less than specified.
.TP
.B \-sm<size>
Process files with size more than specified.
.TP
.B \-ta[mcao]<d>
Process files modified after <d> YYYYMMDDHHMMSS date.
.TP
.B \-tb[mcao]<d>
Process files modified before <d> YYYYMMDDHHMMSS date.
.TP
.B \-tn[mcao]<t>
Process files newer than <t> time.
.TP
.B \-to[mcao]<t>
Process files older than <t> time.
.TP
.B \-ts[m,c,a,p]
Save or restore time (modification, creation, access, preserve).
.TP
.B \-u
Update files.
.TP
.B \-v
List all volumes.
.TP
.B \-ver[n]
File version control.
.TP
.B \-vp
Pause before each volume.
.TP
.BI \-x<file>
Exclude specified file.
.TP
.BI \-x@<list>
Exclude files in specified list file.
.TP
.B \-x@
Read file names to exclude from stdin.
.TP
.B \-y
Assume Yes on all queries.
.SH FILES
.IP "$HOME/.rarrc"
.IP "/etc/.rarrc"
.IP "/etc/rar/.rarrc"
.IP "/usr/lib/.rarrc"
.IP "/usr/local/lib/.rarrc"
.IP "/usr/local/etc/.rarrc"
UnRAR (and RAR) configuration file.
.IP "Syntax: (switches for all commands)"
switches=<any RAR switches separated by spaces>
.IP "Syntax: (switches for specific command)"
switches_<command>=<any RAR switches separated by spaces>
.IP Example:
switches=-m5 -s
.br
switches_a=-m5 -s
.br
switches_x=-o+
.SH SEE ALSO
rar(1)
.SH AUTHORS
This manual page was written by Petr Cech <cech@debian.org> according
to "unrar" for the Debian GNU/Linux system (but may be used by others).
